-- New member-facing "Rules & Guidelines" reference library, editable by
-- admins. Seeded with the org's actual existing EB memos so it isn't empty
-- on first load. Body text is stored plain (line breaks preserved,
-- rendered with white-space: pre-wrap client-side) rather than markdown/
-- rich text, to keep the admin editor a plain textarea.

CREATE TABLE IF NOT EXISTS rules_documents (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           text NOT NULL,
  category        text NOT NULL,
  body            text NOT NULL,
  effective_date  date,
  sort_order      integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rules_documents_category ON rules_documents(category);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rules_documents_updated_at ON rules_documents;
CREATE TRIGGER rules_documents_updated_at
  BEFORE UPDATE ON rules_documents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE rules_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rules_documents_select_all ON rules_documents;
DROP POLICY IF EXISTS rules_documents_insert_all ON rules_documents;
DROP POLICY IF EXISTS rules_documents_update_all ON rules_documents;
DROP POLICY IF EXISTS rules_documents_delete_all ON rules_documents;
CREATE POLICY rules_documents_select_all ON rules_documents FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY rules_documents_insert_all ON rules_documents FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY rules_documents_update_all ON rules_documents FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY rules_documents_delete_all ON rules_documents FOR DELETE TO anon, authenticated USING (true);

INSERT INTO rules_documents (title, category, effective_date, sort_order, body)
SELECT * FROM (VALUES
(
  'Policy on Excused and Unexcused Lates and Absences',
  'Attendance Policy',
  DATE '2025-02-14',
  0,
$body1$To ensure fairness, accountability, and professionalism within our group, we are implementing a clearer policy on excused and unexcused lates and absences during rehearsals. This policy also introduces a contribution system for unexcused tardiness or absences, with proceeds going toward the group's petty cash fund. This fund will support production needs, HR events, competition registration fees, and other immediate financial requirements.

EXCUSED ABSENCES OR TARDINESS
The following reasons will be considered excused upon submission of proper documentation and prior notice:
- Academic classes scheduled between 5:30 PM and 9:00 PM that conflict with rehearsal time.
- Serious or contagious illnesses supported by a medical certificate.
- The passing of an immediate family member or loved one.
- Academic deadlines or examinations due or scheduled during rehearsal hours.
- Official academic group meetings that cannot be rescheduled.
- Emergencies requiring immediate medical attention or involving family hospitalization.
- Official university events occurring during rehearsal time.
- Serious mental health concerns verified by documentation or communicated to HR.

UNEXCUSED
The following will be considered unexcused:
- Late or absent to study for exams or work on academic deadlines that are not due or scheduled during rehearsal time.
- Late or absent due to light illnesses like mild colds, coughs, sneezing, or similar conditions.
- Late or absent due to organizational work or events that are not scheduled during rehearsal time.

PETTY CASH CONTRIBUTIONS
To promote accountability, members with unexcused lates or absences will contribute to the group's petty cash fund, managed by our DM for Finance. Contributions are as follows:
- ₱100 for 2 unexcused lates and/or absences.
- ₱200 for 4 unexcused lates and/or absences.
- ₱300 for 6 unexcused lates and/or absences.

This system resets every term, and fund usage is closely monitored and reported by the Division Manager for Finance. A record of contributions is maintained to ensure transparency.

We trust in your understanding and cooperation as we implement this policy to support the group's operations and maintain the discipline and dedication expected from all members.$body1$
),
(
  'Rehearsal Etiquette Guidelines and Policies',
  'Rehearsal Etiquette',
  DATE '2025-02-14',
  1,
$body2$As we continue to prepare for our upcoming performances and events, it is essential to maintain professionalism, discipline, and respect for one another during rehearsals. The following Rehearsal Etiquette Guidelines and Policies are strictly enforced:

USE OF PHONES AND DEVICES
- Phones are not allowed for reading pieces during rehearsals. Use an iPad, tablet, laptop, or printed copies of your music pieces to minimize distractions.
- Phone usage during rehearsals is strictly prohibited except for emergencies or academic purposes that require immediate attention. For such cases, other devices should be prioritized instead of phones.

MINIMIZING DISRUPTIONS
- Avoid small rehearsals (e.g., singing, humming, or practicing parts individually) while Sir is rehearsing, even if your section is not involved at that moment.
- Do not wear earphones or headphones during rehearsals.
- Do not listen to or study pieces on your own during rehearsals.

RESPECT FOR THE REHEARSAL SPACE
- Eating is prohibited during rehearsals. Avoid bringing smelly food into the rehearsal hall to maintain a pleasant environment.
- Refrain from engaging in small talk or playful behavior with others during rehearsals.

OBSERVING PROPER POSTURE
- Always sit with proper posture during rehearsals. Avoid crossing your legs, slouching, or adopting other inappropriate seating positions that may appear disrespectful or unprofessional.

Your cooperation is crucial for the success of our group. Let's work together to maintain the harmony, professionalism, and excellence that define our team.$body2$
),
(
  'Performance Etiquette Guidelines',
  'Performance Etiquette',
  DATE '2025-05-30',
  2,
$body3$Every performance we give—whether in an intimate gathering or on an international stage—represents not just our individual talent, but the identity and standards of our organization. The following Performance Etiquette Guidelines must be strictly observed in all official performances:

PUNCTUALITY
Arrive on time as scheduled. Tardiness and sudden absences disrupt preparation.

PROPER ATTIRE
Wear the complete and correct performance attire as instructed. Ensure that your attire is clean, well-ironed, and properly fitted. Do not modify your costume without approval.

PROFESSIONAL PREPARATION
Arrive vocally and physically warmed up. Know your pieces and cues.

RESPECT FOR PRE-PERFORMANCE PROTOCOLS
Stay quiet and focused backstage. Follow all team instructions promptly.

STAGE BEHAVIOR
- Enter and exit the stage with grace and discipline. Don't look at the floor.
- Remain composed, alert, and engaged throughout the performance. Avoid unnecessary movements, fidgeting, or adjusting your attire while on stage.

AUDIENCE ENGAGEMENT
- Always maintain good posture, a pleasant facial expression, and confident eye contact.
- Be present in the moment and emotionally connected to the performance, reflecting the mood and message of each piece.

HANDLING MISTAKES GRACEFULLY
Stay calm and continue. Do not react visibly to errors.

POST-PERFORMANCE CONDUCT
- Wait for the conductor's cue to bow and exit the stage.
- Do not break character or interact with the audience until the entire set is finished.
- Thank event organizers, staff, and other performers after the event as appropriate.

REPRESENTING THE CHORALE
Remember that you represent the DLSU Chorale at all times—on stage, backstage, and during interactions with others. Exhibit humility, gratitude, and professionalism in all engagements before, during, and after the performance.$body3$
),
(
  'Concert Etiquette Guidelines for Audience Members',
  'Concert Etiquette',
  DATE '2025-05-30',
  3,
$body4$As representatives of the DLSU Chorale, it is important that we uphold the highest standards of professionalism, discipline, and courtesy—even when we are not performing. Our behavior as audience members directly reflects our commitment to excellence and respect for the choral community. Please observe the following at all times when attending performances:

ARRIVE ON TIME
- Be at the venue 15–30 minutes before the program begins.
- Avoid entering or exiting while a performance is ongoing.

OBSERVE PROPER DRESS CODE
- Follow any prescribed dress code. If none is specified, wear presentable attire.

MAINTAIN SILENCE & PROPER CONDUCT DURING PERFORMANCES
- Refrain from talking, whispering, or making unnecessary noise and offensive comments during performances.
- Show respect for all performers by giving them your full attention.

LIMIT DEVICE USE
- Silence or turn off mobile phones and other electronic devices.
- Do not use phones during the performance unless absolutely necessary.

DO NOT SING OR HUM ALONG
Even if you know the piece, please refrain from singing, humming, or tapping along.

AVOID UNAUTHORIZED PHOTOGRAPHY AND RECORDING
- Do not take photos or videos unless permitted by the organizers.
- Flash photography is strictly prohibited.

APPLAUD APPROPRIATELY
- Clap only after a piece has clearly ended; when in doubt, follow the lead of others.
- Do not interrupt performances with applause at inappropriate moments.

RESPECT THE VENUE AND FELLOW AUDIENCE MEMBERS
- Remain seated during each performance segment.
- Keep proper posture and avoid any behavior that may appear inattentive or disrespectful.

FOLLOW LEADERSHIP AND REPRESENT THE CHORALE WELL
- If attending in an official capacity or as a group, follow instructions from your assigned point person (most of the time EBs).
- Always remember that your conduct represents the entire DLSU Chorale.$body4$
),
(
  'Vocal Health Guidelines for Performing Members',
  'Vocal Health',
  DATE '2025-05-30',
  4,
$body5$Our voices are our primary instrument as choristers, and maintaining good vocal health is essential to sustaining consistent performance quality and preventing long-term strain or injury.

STAY HYDRATED
Drink water regularly throughout the day, especially before and after rehearsals or performances. Avoid excessive caffeine or alcohol intake.

GET ADEQUATE REST
Ensure 7–9 hours of sleep per night to support vocal recovery and general wellness.

WARM UP AND COOL DOWN
Always participate in vocal warm-ups and cool-downs to prepare and restore the voice.

AVOID VOCAL STRAIN
Refrain from shouting, whispering, or speaking loudly for extended periods. Use a healthy speaking voice daily.

REST DURING SICKNESS
If experiencing vocal fatigue or illness, prioritize rest and inform the conductor or team leaders if singing may aggravate your condition.

MAINTAIN GENERAL HEALTH
Eat nutritious meals, manage stress, and exercise regularly to support overall vocal function.

KNOW YOUR LIMITS
Listen to your body. If you feel hoarseness, pain, or fatigue after singing, allow time to rest and recover.

COMMUNICATE VOCAL CONCERNS
If you feel your voice condition has worsened or become concerning, approach Sir Joel directly for guidance and support. You may also consult a medical professional (e.g., ENT specialist, voice doctor, or speech therapist) to ensure your vocal health is properly assessed and cared for.

By caring for your voice, you not only protect your personal health but also contribute to the consistency and quality of our ensemble's sound.$body5$
),
(
  'Performance Request Casting Guidelines and Policies',
  'Casting Policy',
  DATE '2024-08-23',
  5,
$body6$As we prepare for our upcoming performances and professional events, it is essential that we uphold the highest standards of commitment, professionalism, and responsibility. The following Performance Request Casting Guidelines and Policies are in effect:

ELIGIBILITY FOR CASTING
Only members who sign up in advance will be considered for casting. This ensures effective planning and proper role allocation.

NO LAST-MINUTE JOINING
Requests to join at the last minute will not be accepted, except for extreme cases such as a sudden shortage in a specific voice section or unforeseen emergencies.

REHEARSAL REQUIREMENT
- Attendance at all rehearsals during the week of the performance is mandatory. Missing most of the rehearsals for the performance week, regardless of prior attendance, may result in removal from the cast.
- Members who are absent on the day before the performance or during the soundcheck will be automatically disqualified from participating.
- Valid excuses for absences will be reviewed, but missed rehearsals without valid reasons will negatively impact your participation eligibility.

ATTENDANCE ON EVENT DAY
- Members who miss vocalization or rehearsals on the event day, without a valid reason, will not be allowed to perform.
- Valid excuses will not affect your A&A grade, but invalid ones will. Missing the rehearsal for a specific day disqualifies you from that day's performance, even if you were cast for multiple days.

HEALTH CONSIDERATIONS
- Members who experience light coughing on the day of the event may still participate but must wear a mask.
- Members with serious illnesses such as influenza, fever, or other similar conditions will not be allowed to perform, prioritizing the health and safety of the group.

These guidelines are designed to foster accountability, respect, and professionalism within our group, ensuring that our performances are of the highest quality.$body6$
)
) AS seed(title, category, effective_date, sort_order, body)
WHERE NOT EXISTS (SELECT 1 FROM rules_documents);
