-- Fee rules (the schedule members see, e.g. "Late (Rehearsal) — 50") were a
-- hardcoded array in data.ts with a non-functional "Edit" button in the
-- admin UI — no table backed it at all.
CREATE TABLE IF NOT EXISTS fee_rules (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            text NOT NULL,
  amount          numeric(10,2) NOT NULL,
  effective_date  date NOT NULL DEFAULT CURRENT_DATE,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Reuses set_updated_at(), created by 20260425_events_extend.sql.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS fee_rules_updated_at ON fee_rules;
CREATE TRIGGER fee_rules_updated_at
  BEFORE UPDATE ON fee_rules
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE fee_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS fee_rules_select_all ON fee_rules;
DROP POLICY IF EXISTS fee_rules_insert_all ON fee_rules;
DROP POLICY IF EXISTS fee_rules_update_all ON fee_rules;

CREATE POLICY fee_rules_select_all ON fee_rules
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY fee_rules_insert_all ON fee_rules
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY fee_rules_update_all ON fee_rules
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Seed with the same defaults the app previously hardcoded, so the Fee
-- Rules tab isn't empty on first load. Skipped if the table already has rows.
INSERT INTO fee_rules (type, amount, effective_date)
SELECT * FROM (VALUES
  ('Late (Rehearsal)', 50, DATE '2026-01-01'),
  ('Absent — unexcused (Rehearsal)', 150, DATE '2026-01-01'),
  ('Late (Performance)', 200, DATE '2026-01-01'),
  ('Absent — unexcused (Performance)', 500, DATE '2026-01-01')
) AS seed(type, amount, effective_date)
WHERE NOT EXISTS (SELECT 1 FROM fee_rules);
