-- New member-facing feature: file an incident report / testimony (misconduct,
-- concerns, issues). Mirrors the "Testimony Form for Incident Report" the
-- org already uses on paper. account_id_fk/reporter_email are ALWAYS stored
-- (even for anonymous reports) purely so the submitter can be emailed status
-- updates — is_anonymous controls what the HR-facing UI displays, not what's
-- stored. This table is only ever touched through the HR-gated admin screen
-- (see 20260829_create_hr_incident_access.sql) and the member's own
-- submission/my-reports view.

CREATE TABLE IF NOT EXISTS incident_reports (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id_fk         uuid REFERENCES profiles(id) ON DELETE SET NULL,
  reporter_email        text,
  is_anonymous          boolean NOT NULL DEFAULT false,
  witness_name          text,
  school_id             bigint,
  batch_year            text,
  position_role         text,
  person_complained     text,
  incident_when         text,
  incident_where        text,
  people_involved       text,
  what_happened         text NOT NULL,
  impact                text,
  feels_safe            boolean,
  safety_explanation    text,
  additional_notes      text,
  evidence              jsonb NOT NULL DEFAULT '[]'::jsonb,
  consent_signature     text NOT NULL,
  consent_date          date NOT NULL,
  status                text NOT NULL DEFAULT 'Pending' CHECK (status IN (
    'Pending', 'DM Review', 'HR Investigation', 'CM/ACM Investigation',
    'Conductor Investigation', 'CAO Investigation', 'Resolved'
  )),
  verdict               text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_incident_reports_account_id ON incident_reports(account_id_fk);
CREATE INDEX IF NOT EXISTS idx_incident_reports_status ON incident_reports(status);

CREATE TABLE IF NOT EXISTS incident_report_comments (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id     bigint NOT NULL REFERENCES incident_reports(id) ON DELETE CASCADE,
  author_name   text NOT NULL,
  body          text NOT NULL,
  is_feedback   boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_incident_report_comments_report_id ON incident_report_comments(report_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS incident_reports_updated_at ON incident_reports;
CREATE TRIGGER incident_reports_updated_at
  BEFORE UPDATE ON incident_reports
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE incident_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE incident_report_comments ENABLE ROW LEVEL SECURITY;

-- Same permissive anon/authenticated pattern as every other table in this
-- app (custom auth, no Supabase Auth sessions). The real access gate for
-- HR is the password/OTP flow inside AdminIncidents.tsx, not RLS — this app
-- has no per-row Supabase-Auth-based RLS anywhere, so "confidential" here
-- means "not exposed in the UI without the HR password", not enforced at
-- the database layer. Worth knowing given the sensitivity of this data.
DROP POLICY IF EXISTS incident_reports_select_all ON incident_reports;
DROP POLICY IF EXISTS incident_reports_insert_all ON incident_reports;
DROP POLICY IF EXISTS incident_reports_update_all ON incident_reports;
CREATE POLICY incident_reports_select_all ON incident_reports FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY incident_reports_insert_all ON incident_reports FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY incident_reports_update_all ON incident_reports FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS incident_report_comments_select_all ON incident_report_comments;
DROP POLICY IF EXISTS incident_report_comments_insert_all ON incident_report_comments;
CREATE POLICY incident_report_comments_select_all ON incident_report_comments FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY incident_report_comments_insert_all ON incident_report_comments FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Storage bucket for evidence photos/screenshots. Public like every other
-- bucket in this app (avatars, payment-proofs, events) — same caveat as
-- above, URLs are unguessable (random path) but not access-controlled.
INSERT INTO storage.buckets (id, name, public)
VALUES ('incident-evidence', 'incident-evidence', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS incident_evidence_select ON storage.objects;
DROP POLICY IF EXISTS incident_evidence_insert ON storage.objects;

CREATE POLICY incident_evidence_select ON storage.objects
  FOR SELECT TO anon, authenticated USING (bucket_id = 'incident-evidence');
CREATE POLICY incident_evidence_insert ON storage.objects
  FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'incident-evidence');
