CREATE TABLE IF NOT EXISTS event_role_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  committee TEXT NOT NULL,
  role_name TEXT NOT NULL,
  slot_limit INTEGER NOT NULL CHECK (slot_limit > 0),
  major_event_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  exam_required BOOLEAN NOT NULL DEFAULT FALSE,
  ensemble_type TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (event_id, committee, role_name)
);

CREATE TABLE IF NOT EXISTS event_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  member_id BIGINT NOT NULL,
  member_name TEXT NOT NULL,
  committee TEXT,
  section TEXT,
  is_performing BOOLEAN NOT NULL DEFAULT TRUE,
  signup_type TEXT NOT NULL CHECK (signup_type IN ('performing', 'non_performing_role')),
  role_name TEXT NOT NULL DEFAULT '',
  role_committee TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK (status IN ('approved', 'pending', 'rejected')) DEFAULT 'approved',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (event_id, member_id, signup_type, role_name)
);

CREATE INDEX IF NOT EXISTS idx_event_role_slots_event_id ON event_role_slots(event_id);
CREATE INDEX IF NOT EXISTS idx_event_signups_event_id ON event_signups(event_id);
CREATE INDEX IF NOT EXISTS idx_event_signups_status ON event_signups(status);
