-- Music library (sheet music / practice tracks / study guides) had no
-- backing table — AdminMusicLibrary.tsx's add/edit/delete only mutated
-- window.MUSIC_LIBRARY in place, lost on refresh and never shared between
-- sessions or with MemberMusicLibrary.tsx in a different tab/device.
CREATE TABLE IF NOT EXISTS music_categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS music_items (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id  bigint NOT NULL REFERENCES music_categories(id) ON DELETE CASCADE,
  title        text NOT NULL,
  type         text NOT NULL DEFAULT 'Score',
  link         text,
  notes        text,
  event_id_fk  bigint REFERENCES events(event_id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_music_items_category_id ON music_items(category_id);

-- Reuses set_updated_at(), created by 20260425_events_extend.sql.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS music_items_updated_at ON music_items;
CREATE TRIGGER music_items_updated_at
  BEFORE UPDATE ON music_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE music_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE music_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS music_categories_select_all ON music_categories;
DROP POLICY IF EXISTS music_categories_insert_all ON music_categories;
DROP POLICY IF EXISTS music_categories_update_all ON music_categories;
DROP POLICY IF EXISTS music_categories_delete_all ON music_categories;

CREATE POLICY music_categories_select_all ON music_categories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY music_categories_insert_all ON music_categories FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY music_categories_update_all ON music_categories FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY music_categories_delete_all ON music_categories FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS music_items_select_all ON music_items;
DROP POLICY IF EXISTS music_items_insert_all ON music_items;
DROP POLICY IF EXISTS music_items_update_all ON music_items;
DROP POLICY IF EXISTS music_items_delete_all ON music_items;

CREATE POLICY music_items_select_all ON music_items FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY music_items_insert_all ON music_items FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY music_items_update_all ON music_items FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY music_items_delete_all ON music_items FOR DELETE TO anon, authenticated USING (true);
