-- Announcements were entirely mock (data.ts: ANNOUNCEMENTS as a static
-- const, addAnnouncement only touching local React state) — nothing an
-- admin broadcast ever survived a refresh or reached another session.
CREATE TABLE IF NOT EXISTS announcements (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  body        text NOT NULL,
  pinned      boolean NOT NULL DEFAULT false,
  author      text,
  recipients  text NOT NULL DEFAULT 'all',
  created_by  uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON announcements(created_at DESC);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS announcements_select_all ON announcements;
DROP POLICY IF EXISTS announcements_insert_all ON announcements;
DROP POLICY IF EXISTS announcements_delete_all ON announcements;

-- This app uses a custom auth flow (not Supabase Auth sessions), so anon/authenticated
-- roles need explicit policies — same pattern as events, excuse_requests, fee_records.
CREATE POLICY announcements_select_all ON announcements
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY announcements_insert_all ON announcements
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY announcements_delete_all ON announcements
  FOR DELETE
  TO anon, authenticated
  USING (true);
