-- Fees were entirely mock data (see data.ts: "no real DB table yet — always
-- mock") — no fee_records table existed at all. This creates it plus a
-- Storage bucket for payment-proof uploads, matching the events-attachment
-- pattern from 20260820_create_events_storage_bucket.sql.

CREATE TABLE IF NOT EXISTS fee_records (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id_fk         uuid REFERENCES profiles(id) ON DELETE CASCADE,
  fee_date              date NOT NULL,
  type                  text NOT NULL,
  amount                numeric(10,2) NOT NULL,
  reference             text,
  status                text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'pending', 'paid')),
  payment_date          date,
  sender_account        text,
  sender_account_name   text,
  receiver_account      text,
  reference_number      text,
  proof_url             text,
  submitted_at          timestamptz,
  paid_at               date,
  rejection_reason      text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fee_records_account_id ON fee_records(account_id_fk);
CREATE INDEX IF NOT EXISTS idx_fee_records_status ON fee_records(status);

-- Reuses set_updated_at(), created by 20260425_events_extend.sql.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS fee_records_updated_at ON fee_records;
CREATE TRIGGER fee_records_updated_at
  BEFORE UPDATE ON fee_records
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE fee_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS fee_records_select_all ON fee_records;
DROP POLICY IF EXISTS fee_records_insert_all ON fee_records;
DROP POLICY IF EXISTS fee_records_update_all ON fee_records;

-- This app uses a custom auth flow (not Supabase Auth sessions), so anon/authenticated
-- roles need explicit policies — same pattern as events and excuse_requests.
CREATE POLICY fee_records_select_all ON fee_records
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY fee_records_insert_all ON fee_records
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY fee_records_update_all ON fee_records
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Storage bucket for payment proof screenshots/receipts.
INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-proofs', 'payment-proofs', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS payment_proofs_select ON storage.objects;
DROP POLICY IF EXISTS payment_proofs_insert ON storage.objects;

CREATE POLICY payment_proofs_select ON storage.objects
  FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'payment-proofs');

CREATE POLICY payment_proofs_insert ON storage.objects
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'payment-proofs');
